### ISSUE TITLE
Step completion isn't saving

### ISSUE THREAD

**Issue by d10sfan** [HolonProduction/godot_kanban_tasks#19]
Step completion isn't saving after quit. If I create a task and then add steps to it, close Godot, and re-open, those steps being done isn't saved.

If I manually edit the json file and set the done to true then they stay checked.

**Comment by HolonProduction** [comment]
Fixed by e5a02e859f8b7354fac354edee9e3390215cb55a. Update on the AssetLib will likely take some days.
