### ISSUE TITLE
Show details without expanding the entry

### ISSUE THREAD

**Issue by D-T-666** [HolonProduction/godot_kanban_tasks#4]
The experience of having small subtasks within the details would be enhanced if the details were visible without the need to go into edit mode.

**Comment by HolonProduction** [comment]
Do you mean something like this (a preview of the first line)?
![image](https://user-images.githubusercontent.com/99511741/184547772-12492c9f-0f3b-405f-be1c-8e2eb381f4f2.png)

Or more like adding the complete description to the tooltip?

**Comment by D-T-666** [comment]
Yes that's exactly what I meant!

**Comment by HolonProduction** [comment]
Guess I can add this. Will make it a setting though because I for my part think it makes the board a little bit cluttered when there are many tasks.

**Comment by HolonProduction** [comment]
New version is available in the asset lib.
